# GENERATED by `caveman enable hermes`. Thin fail-open lifecycle adapter.
# Source contract: Hermes v0.18 plugin register(ctx) and hook signatures in
# ~/.hermes/hermes-agent/website/docs/guides/build-a-hermes-plugin.md.
import hashlib
import json
import re
import subprocess

_CAVEMAN_CMD = "/home/s4w3d0ff/.npm/_npx/1915db09411464bc/node_modules/.bin/caveman"
_CAVEMAN_PRE = []


def _digest(value):
    try:
        raw = json.dumps(value, sort_keys=True, ensure_ascii=False, default=str).encode("utf-8")
        return {"bytes": len(raw), "sha256": "sha256:" + hashlib.sha256(raw).hexdigest()}
    except Exception:
        return {"bytes": 0}


def _task_type(value):
    try:
        text = json.dumps(value, ensure_ascii=False, default=str).lower()
    except Exception:
        return "general"
    def has(*terms):
        return any(term in text for term in terms)
    if has("migration", "migrate", "schema change", "backfill", "rollback"):
        return "migration"
    if has("bug", "fix", "broken", "regression", "crash", "error", "incorrect"):
        return "bugfix"
    if has("investigate", "diagnose", "root cause", "why does", "trace"):
        return "investigation"
    if has("refactor", "restructure", "reorganize", "cleanup"):
        return "refactor"
    if has("review", "audit", "critique", "assess"):
        return "review"
    if has("verify", "verification", "prove", "validate", "check that"):
        return "verification"
    if has("build", "implement", "add", "create", "ship", "feature"):
        return "feature"
    return "general"


def _task_terms(value):
    try:
        text = json.dumps(value, ensure_ascii=False, default=str)
    except Exception:
        return []
    stop = {"about", "after", "agent", "before", "build", "change", "code", "create", "from", "have", "help", "implement", "into", "make", "please", "project", "repository", "should", "spec", "task", "that", "then", "there", "these", "they", "this", "through", "user", "want", "what", "when", "where", "which", "with", "would", "your"}
    out = []
    for raw in re.findall(r"[A-Za-z][A-Za-z0-9_./-]{2,63}", text):
        term = raw.lower().strip("-./")
        if not term or ".." in term or term in stop or term in out:
            continue
        if re.match(r"^(?:sk|pk|rk|ghp|github_pat|xox[baprs]|akia)[-_]", term, re.I) or re.match(r"^[a-z0-9_-]{40,}$", term, re.I):
            continue
        out.append(term)
        if len(out) == 12:
            break
    return out


def _task_continuation(value):
    if not isinstance(value, str):
        return False
    prompt = value.strip().lower()
    if not prompt or len(prompt) > 160 or len(prompt.split()) > 14:
        return False
    return re.match(r"^(?:pleases+)?(?:continue|go ahead|keep going|proceed|do (?:it|that)|fix (?:it|that)|retry|try again|explain (?:it|that)|what do you mean|yes|yep|yeah|why??|how??)[.!?s]*$", prompt) is not None


def _call(event, payload=None):
    try:
        body = {"event_name": event}
        if isinstance(payload, dict):
            body.update(payload)
        proc = subprocess.run(
            [_CAVEMAN_CMD, *_CAVEMAN_PRE, "native-hook", "hermes", event],
            input=json.dumps(body, ensure_ascii=False),
            text=True,
            capture_output=True,
            timeout=1,
        )
        if proc.returncode != 0 or not proc.stdout.strip():
            return None
        out = json.loads(proc.stdout)
        return out if isinstance(out, dict) else None
    except Exception:
        return None


def _on_session_start(session_id=None, model=None, platform=None, **kwargs):
    _call("SessionStart", {"session_id": session_id, "model": model, "surface": platform})


def _pre_llm_call(session_id=None, user_message=None, model=None, platform=None, **kwargs):
    out = _call("UserPromptSubmit", {
        "session_id": session_id,
        "model": model,
        "surface": platform,
        "prompt": _digest(user_message),
        "task_type": _task_type(user_message),
        "task_terms": _task_terms(user_message),
        "task_continuation": _task_continuation(user_message),
    })
    context = out.get("context") if isinstance(out, dict) else None
    return {"context": context} if isinstance(context, str) and context else None


def _pre_tool_call(tool_name=None, args=None, task_id=None, **kwargs):
    _call("PreToolUse", {"session_id": task_id, "tool_name": tool_name, "tool_input": _digest(args)})


def _post_tool_call(tool_name=None, args=None, result=None, task_id=None, duration_ms=None, **kwargs):
    _call("PostToolUse", {
        "session_id": task_id,
        "tool_name": tool_name,
        "tool_input": _digest(args),
        "tool_output": _digest(result),
        "duration_ms": duration_ms,
    })


def _pre_verify(task_id=None, **kwargs):
    _call("Stop", {"session_id": task_id})


def _post_llm_call(session_id=None, model=None, **kwargs):
    _call("ModelAfter", {"session_id": session_id, "model": model})


def _on_session_end(session_id=None, **kwargs):
    _call("SessionEnd", {"session_id": session_id})


def _on_session_finalize(session_id=None, **kwargs):
    _call("SessionEnd", {"session_id": session_id})


def register(ctx):
    ctx.register_hook("on_session_start", _on_session_start)
    ctx.register_hook("pre_llm_call", _pre_llm_call)
    ctx.register_hook("pre_tool_call", _pre_tool_call)
    ctx.register_hook("post_tool_call", _post_tool_call)
    ctx.register_hook("pre_verify", _pre_verify)
    ctx.register_hook("post_llm_call", _post_llm_call)
    ctx.register_hook("on_session_end", _on_session_end)
    ctx.register_hook("on_session_finalize", _on_session_finalize)
